#include <iostream>
#include <vector>
#include <unordered_set>
#include <set>
#include <unordered_map>
#include <queue>
#include <algorithm>
#include <functional>
using namespace std;

class solution{
    int UKG_2(int n, vector<int> pos, vector<int> city){
        unordered_map<int,int> posmin;
        unordered_map<int,int> posmax;

        for(int i = 0; i < city.size(); i++){
            auto iter = posmin.begin();
            for(int j = 0; j < )
        }

    }
};
int main(){   // people#0 1 2 3 4 5 6 7
    vector<int> city = {7,1,2,4,5,5,5,9};
    vector<int> pos =  {6,8,7,4,5,3,1,9};


    int number = 8;
}